Tampere/trevaka

service/build.gradle.kts
service/src/main/kotlin/fi/tampere/trevaka/person/config/PersonConfiguration.kt
service/src/test/kotlin/fi/tampere/trevaka/person/service/DvvModificationsServiceClientIT.kt
service/src/test/resources/__files/modifications-client/first-modification-token-response-ok.json
service/src/test/resources/__files/modifications-client/modifications-response-ok.json

Requires https://github.com/espoon-voltti/evaka/pull/682

Add authentication to person modification http requests

---

frontend/tampere/citizen.tsx
frontend/tampere/mapConfig.tsx

Requires https://github.com/espoon-voltti/evaka/pull/716

Add map config

---

service/build.gradle.kts
service/buildSrc/src/main/kotlin/TrevakaServiceDeps.kt
service/src/main/kotlin/fi/tampere/trevaka/message/config/MessageConfiguration.kt
service/src/main/resources/messages.yaml
service/src/test/kotlin/fi/tampere/trevaka/message/MessageProviderTest.kt

Requires https://github.com/espoon-voltti/evaka/pull/709

Add sfi messages

---

service/build.gradle.kts
service/buildSrc/src/main/kotlin/TrevakaServiceDeps.kt
service/src/main/kotlin/fi/tampere/trevaka/TrevakaProperties.kt
service/src/main/kotlin/fi/tampere/trevaka/invoice/config/InvoiceConfiguration.kt
service/src/main/kotlin/fi/tampere/trevaka/invoice/service/TrevakaInvoiceClient.kt
service/src/main/resources/application-trevaka-local.yaml
service/src/test/kotlin/fi/tampere/trevaka/invoice/service/TrevakaInvoiceClientTest.kt
service/src/test/resources/application-integration-test.yml

There is going to be different base url for each service in ipaas.

Refactor invoice url

---

frontend/tampere/citizen.tsx
frontend/tampere/mapConfig.tsx

Requires https://github.com/espoon-voltti/evaka/pull/729

Map address search rectangular defs for Tampere

---

frontend/tampere/fiCustomizations.tsx

NOTE! Needs https://github.com/espoon-voltti/evaka/pull/801

TREV-142 customize early childhood education application texts

---

frontend/tampere/featureFlags.tsx

Requires https://github.com/espoon-voltti/evaka/pull/871

daycare application has service need options enabled

---

frontend/tampere/featureFlags.tsx
frontend/tampere/fiCustomizations.tsx

Also add missing text to daycare application
Needs https://github.com/espoon-voltti/evaka/pull/913

Disable daily times from daycare application

---

frontend/tampere/employee.tsx
frontend/tampere/fiCustomizations.tsx

TREV-222 needs https://github.com/espoon-voltti/evaka/pull/992 to be done

TREV-222, TREV-221, TREV-227: text changes

---

service/src/main/resources/WEB-INF/templates/tampere/fee-decision/decision.html
service/src/test/kotlin/fi/tampere/trevaka/invoice/service/PDFServiceTest.kt

Fix fee decision template render

---

service/src/main/kotlin/fi/tampere/trevaka/message/config/MessageConfiguration.kt
service/src/main/resources/WEB-INF/templates/tampere/fee-decision/decision.html
service/src/main/resources/WEB-INF/templates/tampere/fee-decision/voucher-value-decision.html
service/src/main/resources/WEB-INF/templates/tampere/shared/common.html

Also updates decision person name format to match with fee decision.

Fix fee decision empty address

---

service/src/main/resources/db/migration/afterMigrate__care_areas.sql

Care area code is required in InvoiceGenerator.
See https://github.com/espoon-voltti/evaka/blob/6448d5a0e917944aa9571e5d7578f81ee1abe4e9/service/src/main/kotlin/fi/espoo/evaka/invoicing/service/InvoiceGenerator.kt#L194-L195

Fix invoice generator

---

service/src/main/resources/db/migration/afterMigrate__care_areas.sql

Add static ids for care areas

---

LICENSES/OFL-1.1.txt
compose/docker-compose-dbs.yml
compose/ecosystem.config.js
frontend/package.json
frontend/src/e2e/common/tampere-dev-api.ts
frontend/src/e2e/jest.config.ts
frontend/src/e2e/specs/0_citizen/citizen-applications.spec.ts
frontend/src/e2e/specs/0_citizen/citizen-footer.spec.ts
frontend/src/e2e/specs/0_citizen/citizen-map.spec.ts
frontend/src/e2e/tsconfig.json
frontend/src/e2e/tsconfig.json.license
frontend/tampere/assets/favicon.ico.license
frontend/tampere/common.tsx
frontend/tampere/employeeMobile.tsx
frontend/tampere/fiCustomizations.tsx
frontend/tampere/footer-logo-citizen.png.license
frontend/tampere/mapConfig.tsx
frontend/tampere/tampere-theme.tsx
frontend/yarn.lock
service/src/main/kotlin/fi/tampere/trevaka/database/DataInitializers.kt
service/src/main/kotlin/fi/tampere/trevaka/database/DevDataInitializer.kt
service/src/main/kotlin/fi/tampere/trevaka/dev/TampereDevApi.kt
service/src/main/resources/dev-data/reset-tampere-database-for-e2e-tests.sql

Needs changes to evaka (https://github.com/espoon-voltti/evaka/pull/1384)

TREV-295 e2e tests for citizen applications tab views

---

frontend/src/e2e/specs/0_citizen/citizen-applications.spec.ts
frontend/src/e2e/specs/0_citizen/citizen-income.spec.ts
frontend/tampere/employee.tsx
frontend/tampere/employeeMobile.tsx
frontend/tampere/enCustomizations.tsx
frontend/tampere/featureFlags.tsx
frontend/tampere/fiCustomizations.tsx

Includes also TREV-333 (mobile customizations) and TREV-339 (employee's first login welcome text)
Needs https://github.com/espoon-voltti/evaka/pull/1477

TREV-306 income text customizations

---

service/src/main/kotlin/fi/tampere/trevaka/emailclient/config/EmailConfiguration.kt

Fix email dashes

---

.circleci/config.yml

This will probably fix error code 129 in frontend build.

Increase frontend core build resources

---

.circleci/config.yml

Fixes frontend reload notification.

Make APP_COMMIT available in the frontend

---

service/src/main/kotlin/fi/tampere/trevaka/TrevakaProperties.kt
service/src/main/kotlin/fi/tampere/trevaka/invoice/config/InvoiceConfiguration.kt
service/src/main/kotlin/fi/tampere/trevaka/invoice/service/TrevakaInvoiceClient.kt
service/src/main/resources/application-trevaka-local.yaml
service/src/test/kotlin/fi/tampere/trevaka/invoice/service/TrevakaInvoiceClientTest.kt
service/src/test/resources/application-integration-test.yml

Includes some cleanup to invoice client.

Update invoice material codes

---

.circleci/config.yml
service/Dockerfile
service/buildSrc/src/main/kotlin/TrevakaServiceDeps.kt

Evaka update/2021 11 24

---

service/src/main/resources/WEB-INF/templates/tampere/fee-decision/voucher-value-decision.html
service/src/main/resources/WEB-INF/templates/tampere/fee-decision/voucher-value-decision.properties
service/src/test/kotlin/fi/tampere/trevaka/invoice/service/PDFServiceTest.kt

Adds basic relief things to voucher value decision. Texts and visuals are evaluated and changed later on..

TREV-376 add relief stuff to voucher value decision

---

service/src/main/resources/WEB-INF/templates/tampere/fee-decision/decision.html
service/src/main/resources/WEB-INF/templates/tampere/fee-decision/voucher-value-decision.html
service/src/main/resources/WEB-INF/templates/tampere/fee-decision/voucher-value-decision.properties
service/src/test/kotlin/fi/tampere/trevaka/invoice/service/PDFServiceTest.kt

Add fee decision maker support

---

frontend/.gitignore
frontend/src/e2e/specs/0_citizen/citizen-applications.spec.ts

ExternalLink implementation changed.

Evaka update/2022 01 18

---

frontend/tampere/employee.tsx
service/src/main/kotlin/fi/tampere/trevaka/invoice/config/InvoiceConfiguration.kt
service/src/main/kotlin/fi/tampere/trevaka/invoice/service/TrevakaInvoiceClient.kt
service/src/test/kotlin/fi/tampere/trevaka/invoice/service/TrevakaInvoiceClientTest.kt

Also adds initial invoice product provider to fix build.

Add decision types

---

service/src/main/resources/db/migration/afterMigrate__holidays.sql

Add initial holidays for 2019-2022

---

service/src/main/kotlin/fi/tampere/trevaka/TampereConfig.kt

Tampere has 20 operational days

Evaka update/2022 01 28

---

frontend/src/e2e/common/translations-check-utils.ts
frontend/src/e2e/specs/1_employee/employee_translations.spec.ts
frontend/src/e2e/specs/2_mobile/mobile_translations.spec.ts

Text checks for employee and mobile

---

service/build.gradle.kts
service/src/main/resources/application-trevaka.yaml

This will add git commit details to info endpoint.

Add git properties gradle plugin

---

service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt

Access control API was changed.

Fix action rule mapping

---

service/src/main/kotlin/fi/tampere/trevaka/invoice/service/TrevakaInvoiceClient.kt
service/src/test/kotlin/fi/tampere/trevaka/invoice/service/TrevakaInvoiceClientTest.kt

All zero sum invoices (including those of people not having a social security number) are not sent to SAP. They still are marked as sent.

TREV-676 do not send zero sum invoices to SAP, but set as sent

---

.circleci/config.yml
service/buildSrc/src/main/kotlin/TrevakaServiceDeps.kt

apigw dockerfile was changed upstream

Evaka update/2022 05 24

---

service/src/main/kotlin/fi/tampere/trevaka/invoice/service/TrevakaInvoiceClient.kt
service/src/test/resources/invoice-client/sales-order-request-codebtor.xml

Previous spec was wrong, head of family should in the firstNames.

Fix invoice with codebtor

---

frontend/tampere/employee.tsx

- modified text as per requirement

TREV-724: Added further instructions for marking an absence

---

frontend/tampere/enCustomizations.tsx

- text is a slightly modified copy of the corresponding statement translation from Espoo
- further review for regional modifications required 
- provided links are partially to Finnish resources, see comments for details

TREV-720: Accessibility statement translation to English

---

service/src/main/kotlin/fi/tampere/trevaka/person/config/PersonConfiguration.kt

Attempt to fix random "connection reset" errors.

Fix connection reset error

---

service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt

Fixes unit's attendances-tab for special education teachers.

Update attendance reservation permissions

---

service/src/main/resources/db/migration/afterMigrate__preschool_terms.sql

Add preschool terms

---

service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt

Unit supervisors allowed to decide assistance decisions.

Add assistance decision report permissions

---

service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt

Staff without group acl should see curriculum documents.

Add curriculum document permitted actions

---

service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt

Granted staff-role global access to report page and unit level access to child attendance reports.

TREV-791: Staff access to child attendance reports

---

frontend/tampere/enCustomizations.tsx
frontend/tampere/fiCustomizations.tsx

Added further information for citizen application instructions

---

scheduled-tasks/reporting/Dockerfile
scheduled-tasks/reporting/db_to_csv.sh

Removed dropped tables from ignore list.
Also added a way to install latest security fixes.

Reporting scheduled task updates

---

scheduled-tasks/reporting/db_to_csv.sh

This feels like table which is not needed in reporting.

Ignore income_notification table from reporting

---

frontend/tampere/employee.tsx

NOTE! This change is needed from 08/2023

Changed the title of child details' vasu-section [08/2023]

---

frontend/src/e2e/specs/0_citizen/citizen-applications.spec.ts
frontend/tampere/enCustomizations.tsx
frontend/tampere/fiCustomizations.tsx

https://github.com/Tampere/trevaka/pull/311 part 2

Update customer service opening hours

---

service/build.gradle.kts
service/src/main/resources/application-trevaka.yaml

This reverts commit 690360d4c1255e21873271c0bcb3265412289278, reversing changes made to f265fc59979f7ce277e0ee3262f25ef7fe074da9.
Apigw version is available at `/api/internal/version` without authentication.

Revert "Merge pull request #174 from Tampere/info-endpoint"

---

service/src/main/resources/WEB-INF/templates/tampere/shared/daycare-correction.html
service/src/main/resources/WEB-INF/templates/tampere/shared/daycare-correction.properties
service/src/main/resources/WEB-INF/templates/tampere/shared/preschool-correction.html

Also fixes mock data for preschool correction address.

Update daycare correction address

---

service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt

Full access for ECES of unit to TEMPORARY_EMPLOYEE functionality.

Eces temporary employee rights

---

service/src/main/kotlin/fi/tampere/trevaka/titania/Titania.kt
service/src/main/kotlin/fi/tampere/trevaka/titania/TitaniaService.kt
service/src/test/kotlin/fi/tampere/trevaka/titania/TitaniaControllerTest.kt

Update empty employee number handling

---

service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt

- finance admin should see assistance factor only
- director should see everything related to assistance

Fix assistance rules

---

.circleci/config.yml
auth/Dockerfile

All environments already uses newer stuff.

Cleanup backward compatibility

---

service/build.gradle.kts
service/src/test/kotlin/fi/tampere/trevaka/AbstractIntegrationTest.kt
service/src/test/kotlin/fi/tampere/trevaka/AbstractTampereIntegrationTest.kt
service/src/test/kotlin/fi/tampere/trevaka/assistanceneed/decision/AssistanceNeedDecisionServiceTest.kt
service/src/test/kotlin/fi/tampere/trevaka/assistanceneed/decision/PreschoolAssistanceNeedDecisionServiceTest.kt
service/src/test/kotlin/fi/tampere/trevaka/database/DevDataInitializerTest.kt
service/src/test/kotlin/fi/tampere/trevaka/decision/service/DecisionServiceTest.kt
service/src/test/kotlin/fi/tampere/trevaka/email/EmailMessageProviderTest.kt
service/src/test/kotlin/fi/tampere/trevaka/invoice/config/InvoiceConfigurationIT.kt
service/src/test/kotlin/fi/tampere/trevaka/invoice/service/PDFServiceTest.kt
service/src/test/kotlin/fi/tampere/trevaka/invoice/service/TrevakaInvoiceClientIT.kt
service/src/test/kotlin/fi/tampere/trevaka/invoicing/domain/VoucherValueDecisionsTest.kt
service/src/test/kotlin/fi/tampere/trevaka/message/MessageProviderTest.kt
service/src/test/kotlin/fi/tampere/trevaka/person/service/DvvModificationsServiceClientIT.kt
service/src/test/kotlin/fi/tampere/trevaka/person/service/PersonDetailsServiceIT.kt
service/src/test/kotlin/fi/tampere/trevaka/reservation/ReservableRangeTest.kt
service/src/test/kotlin/trevaka/AbstractIntegrationTest.kt
service/src/test/kotlin/trevaka/FuelExtensions.kt
service/src/test/kotlin/trevaka/IntegrationTestConfiguration.kt

Move integration test spring profiles configuration from gradle config to kotlin code + other cleanups.
This enables to test other contexts later.

Integration test refactor

---

service/src/main/kotlin/fi/tampere/trevaka/person/config/PersonConfiguration.kt

Regression from 49cf103965a6acc212b920874ae833a60b18b0ee

Fix fuel manager bean

---

service/src/main/resources/WEB-INF/templates/tampere/assistance-preschool/decision.html
service/src/main/resources/WEB-INF/templates/tampere/assistance-preschool/decision.properties

https://github.com/espoon-voltti/evaka/pull/4529

Add preschool assistance decision legal instructions text

---

service/src/main/kotlin/fi/hameenkyro/evaka/HameenkyroProperties.kt
service/src/main/kotlin/fi/vesilahti/evaka/VesilahtiProperties.kt

This makes easier to add new properties to infra code beforehand.

Ignore unknown fields in properties

---

service/src/main/kotlin/fi/tampere/trevaka/reports/ReportsController.kt

Really old commit which should be useful now that we are going to do new data migrations. This relates to how Tampere data was manually fixed after the migration & freeze.

Fix freeze voucher value report taken at

---

service/src/main/resources/db/data/vesilahti/afterMigrate__care_areas.sql

Area is required to create units.

Add Vesilahti area

---

service/src/main/kotlin/fi/vesilahti/evaka/VesilahtiConfig.kt

https://github.com/Tampere/trevaka/pull/658 removed some beans.

Fix Vesilahti beans

---

service/src/main/kotlin/fi/hameenkyro/evaka/HameenkyroConfig.kt
service/src/main/kotlin/fi/hameenkyro/evaka/database/DataInitializers.kt
service/src/main/kotlin/fi/hameenkyro/evaka/database/DevDataInitializer.kt
service/src/main/kotlin/fi/hameenkyro/evaka/security/HameenkyroActionRuleMapping.kt
service/src/main/kotlin/fi/vesilahti/evaka/VesilahtiConfig.kt
service/src/main/kotlin/fi/vesilahti/evaka/database/DataInitializers.kt
service/src/main/kotlin/fi/vesilahti/evaka/database/DevDataInitializer.kt
service/src/main/kotlin/fi/vesilahti/evaka/security/VesilahtiActionRuleMapping.kt
service/src/main/resources/dev-data/hameenkyro-dev-data.sql
service/src/main/resources/dev-data/vesilahti-dev-data.sql
service/src/test/kotlin/fi/hameenkyro/evaka/database/DevDataInitializerTest.kt
service/src/test/kotlin/fi/vesilahti/evaka/database/DevDataInitializerTest.kt

https://voltti.atlassian.net/browse/TREV-1129

TREV-1129 PIN-koodin asettaminen ensimmäisen kirjautumisen yhteydessä

---

service/src/main/kotlin/fi/hameenkyro/evaka/invoice/service/S3Sender.kt
service/src/main/kotlin/fi/vesilahti/evaka/invoice/service/S3Sender.kt

Bucket may later contain other files.

Add prefix for invoice files

---

service/src/main/resources/application-hameenkyro_evaka.yaml
service/src/main/resources/application-tampere_evaka.yaml
service/src/main/resources/application-trevaka-local.yaml
service/src/main/resources/application-vesilahti_evaka.yaml
service/src/test/resources/application-integration-test.yml

Changed from evaka_municipality_local to evaka_municipality_it.

Fix service test database name

---

frontend/hameenkyro/employee.tsx
frontend/hameenkyro/employeeMobile.tsx
frontend/hameenkyro/enCustomizations.tsx
frontend/hameenkyro/fiCustomizations.tsx
frontend/vesilahti/employee.tsx
frontend/vesilahti/employeeMobile.tsx
frontend/vesilahti/enCustomizations.tsx
frontend/vesilahti/fiCustomizations.tsx

https://voltti.atlassian.net/browse/TREV-1151

TREV-1151 "Sopimuksenmukainen poissaolo" teksti -> "suunniteltu poissaolo"

---

service/src/main/resources/WEB-INF/templates/hameenkyro/daycare/voucher/decision.properties
service/src/main/resources/messages-vesilahti.yaml

Also fixes link in Vesilahti decision content message

Hameenkyro daycare voucher link fix

---

auth/realms/tampere/citizens-realm-export.json
auth/realms/tampere/employees-realm-export.json
mock/identification/src/main/resources/application.yml

We are using entity id validation in prod so add it to local also.

Add idp entity id validation to auth

---

service/src/main/resources/db/data/hameenkyro/afterMigrate__employee_number_fix.sql
service/src/main/resources/db/data/hameenkyro/afterMigrate__service_need_options.sql
service/src/main/resources/db/data/tampere/afterMigrate__employee_number_fix.sql
service/src/main/resources/db/data/vesilahti/afterMigrate__employee_number_fix.sql
service/src/main/resources/db/data/vesilahti/afterMigrate__service_need_options.sql

Data have been fixed in every environment.

Cleanup after migrate scripts

---

service/src/main/kotlin/fi/lempaala/evaka/LempaalaConfig.kt

Change value to Friday 09:00 (1 week + 3 days before)

Update citizenReservationThresholdHours in lempäälä config

---

service/src/main/kotlin/fi/hameenkyro/evaka/invoice/service/S3Sender.kt
service/src/main/kotlin/fi/vesilahti/evaka/invoice/service/S3Sender.kt

Update invoice filename

---

service/src/main/kotlin/fi/hameenkyro/evaka/invoice/service/S3Sender.kt
service/src/main/kotlin/fi/vesilahti/evaka/invoice/service/S3Sender.kt

Change encoding from UTF-8 to ISO-8859-1 (AKA Latin-1)

Change character encoding of hämeenkyrö invoices

---

compose/db/entry/init_evaka.sh

This makes possible to run core application and tests.
Also adds `migration` schema for every db (to be used by `effica-trevaka-parser`).

Add espoo db

---

service/src/main/kotlin/fi/lempaala/evaka/LempaalaIncomeCoefficientMultiplierProvider.kt
service/src/main/kotlin/fi/lempaala/evaka/LempaalaIncomeTypesProvider.kt

Required for finance decisions.

Add income types & coefficient multiplier providers

---

service/src/main/kotlin/fi/kangasala/evaka/KangasalaConfig.kt
service/src/main/kotlin/fi/lempaala/evaka/LempaalaConfig.kt
service/src/main/kotlin/fi/lempaala/evaka/mealintegration/LempaalaMealTypeMapper.kt
service/src/main/kotlin/fi/nokiankaupunki/evaka/NokiaConfig.kt
service/src/main/kotlin/fi/nokiankaupunki/evaka/mealintegration/NokiaMealTypeMapper.kt
service/src/main/kotlin/fi/pirkkala/evaka/PirkkalaConfig.kt
service/src/main/kotlin/fi/pirkkala/evaka/mealintegration/PirkkalaMealTypeMapper.kt
service/src/main/kotlin/fi/ylojarvi/evaka/YlojarviConfig.kt
service/src/main/kotlin/fi/ylojarvi/evaka/mealintegration/YlojarviMealTypeMapper.kt
service/src/test/kotlin/fi/kangasala/evaka/mealintagration/KangasalaMealTypeMapper.kt
service/src/test/kotlin/fi/lempaala/evaka/mealintagration/LempaalaMealTypeMapper.kt
service/src/test/kotlin/fi/nokiankaupunki/evaka/mealintagration/NokiaMealTypeMapper.kt
service/src/test/kotlin/fi/pirkkala/evaka/mealintagration/PirkkalaMealTypeMapper.kt
service/src/test/kotlin/fi/ylojarvi/evaka/mealintagration/YlojarviMealTypeMapper.kt

Jamix `mealID` mappers for Kangasala, Lempäälä, Nokia, Pirkkala and Ylojärvi

Per municipality meal id mappers

---

service/src/main/resources/WEB-INF/templates/hameenkyro/assistance-preschool/decision.properties

https://voltti.atlassian.net/browse/TREV-1226

Change jurisdiction text in hämeenkyrö preschool assistance decision

---

service/src/main/resources/WEB-INF/templates/ylojarvi/fee-decision/decision.html
service/src/main/resources/WEB-INF/templates/ylojarvi/fee-decision/decision.properties
service/src/main/resources/WEB-INF/templates/ylojarvi/fee-decision/voucher-value-decision.html
service/src/main/resources/WEB-INF/templates/ylojarvi/fee-decision/voucher-value-decision.properties
service/src/main/resources/WEB-INF/templates/ylojarvi/shared/daycare-correction.html
service/src/main/resources/WEB-INF/templates/ylojarvi/shared/daycare-correction.properties

https://voltti.atlassian.net/browse/TREV-1172

Change ylöjärvi decision approver details

---

service/src/main/resources/WEB-INF/templates/ylojarvi/fee-decision/voucher-value-decision.properties

https://voltti.atlassian.net/browse/TREV-1240

Change ylöjärvi voucher value decision approver details

---

service/src/main/resources/WEB-INF/templates/hameenkyro/assistance-preschool/decision.properties
service/src/main/resources/WEB-INF/templates/kangasala/assistance-preschool/decision.properties
service/src/main/resources/WEB-INF/templates/lempaala/assistance-preschool/decision.properties
service/src/main/resources/WEB-INF/templates/pirkkala/assistance-preschool/decision.properties
service/src/main/resources/WEB-INF/templates/tampere/assistance-preschool/decision.properties
service/src/main/resources/WEB-INF/templates/vesilahti/assistance-preschool/decision.properties
service/src/main/resources/WEB-INF/templates/ylojarvi/assistance-preschool/decision.properties

Delete lone § character from preschool assistance templates

---

service/build.gradle.kts

Version is defined in eVaka core.

Remove kotlin reflect version

---

service/src/main/kotlin/fi/nokiankaupunki/evaka/NokiaProperties.kt
service/src/main/kotlin/fi/nokiankaupunki/evaka/invoice/service/S3Sender.kt
service/src/main/kotlin/fi/pirkkala/evaka/PirkkalaProperties.kt
service/src/main/kotlin/fi/pirkkala/evaka/invoice/service/S3Sender.kt
service/src/main/kotlin/fi/ylojarvi/evaka/YlojarviProperties.kt
service/src/main/kotlin/fi/ylojarvi/evaka/invoice/service/S3Sender.kt
service/src/main/resources/application-nokia_evaka.yaml
service/src/main/resources/application-pirkkala_evaka.yaml
service/src/main/resources/application-trevaka-local.yaml
service/src/main/resources/application-ylojarvi_evaka.yaml
service/src/test/resources/application-integration-test.yml

Use format "invoices/municipalityCode_invoiceType'yyyyMMddHHmm'.dat"
https://voltti.atlassian.net/browse/TREV-1229

Rename invoice file in 2nd wave municipalities

---

service/src/main/kotlin/fi/nokiankaupunki/evaka/invoice/service/S3Sender.kt
service/src/main/kotlin/fi/pirkkala/evaka/invoice/service/S3Sender.kt
service/src/main/kotlin/fi/ylojarvi/evaka/invoice/service/S3Sender.kt

Add a missing underscore between invoiceType and timestamp: "invoices/municipalityCode_invoiceType_'yyyyMMddHHmm'.dat"

Add an underscore in 2nd wave invoice file name

---

.circleci/config.yml
README.md
docker-compose.yml
frontend/package.json

When using `docker compose --profile auth --profile evaka up`.

Fix apigw-auth integration in docker compose

---

frontend/hameenkyro/enCustomizations.tsx
frontend/hameenkyro/fiCustomizations.tsx
frontend/kangasala/enCustomizations.tsx
frontend/kangasala/fiCustomizations.tsx
frontend/lempaala/enCustomizations.tsx
frontend/lempaala/fiCustomizations.tsx
frontend/nokia/enCustomizations.tsx
frontend/nokia/fiCustomizations.tsx
frontend/orivesi/enCustomizations.tsx
frontend/orivesi/fiCustomizations.tsx
frontend/pirkkala/enCustomizations.tsx
frontend/pirkkala/fiCustomizations.tsx
frontend/ylojarvi/enCustomizations.tsx
frontend/ylojarvi/fiCustomizations.tsx

https://voltti.atlassian.net/browse/TREV-1286

Update accessibility statement & links for feedback/privacy policy in 2nd/3rd/4th wave

---

service/src/main/kotlin/fi/hameenkyro/evaka/invoice/service/HameenkyroInvoiceIntegrationClient.kt
service/src/main/kotlin/fi/kangasala/evaka/invoice/service/KangasalaInvoiceIntegrationClient.kt
service/src/main/kotlin/fi/lempaala/evaka/invoice/service/LempaalaInvoiceIntegrationClient.kt
service/src/main/kotlin/fi/nokiankaupunki/evaka/invoice/service/NokiaInvoiceIntegrationClient.kt
service/src/main/kotlin/fi/orivesi/evaka/invoice/service/OrivesiInvoiceIntegrationClient.kt
service/src/main/kotlin/fi/pirkkala/evaka/invoice/service/PirkkalaInvoiceIntegrationClient.kt
service/src/main/kotlin/fi/vesilahti/evaka/invoice/service/VesilahtiInvoiceIntegrationClient.kt
service/src/main/kotlin/fi/ylojarvi/evaka/invoice/service/YlojarviInvoiceIntegrationClient.kt

Only generate and send invoices if totalPrice != 0
https://voltti.atlassian.net/browse/TREV-1298

Filter out zero sum invoices

---

service/src/main/resources/WEB-INF/templates/hameenkyro/fee-decision/voucher-value-decision.properties

https://voltti.atlassian.net/browse/TREV-1234

Change email address in hämeenkyrö voucher decision

---

frontend/ylojarvi/employee.tsx
frontend/ylojarvi/fiCustomizations.tsx
service/src/main/resources/WEB-INF/templates/ylojarvi/assistance-preschool/decision.properties
service/src/main/resources/WEB-INF/templates/ylojarvi/assistance/decision.properties

https://voltti.atlassian.net/browse/TREV-1287

Change jurisdiction text in ylöjärvi assistance templates

---

frontend/hameenkyro/employee.tsx
frontend/hameenkyro/fiCustomizations.tsx

https://voltti.atlassian.net/browse/TREV-1290

Change jurisdiction text in hämeenkyrö frontend

---

frontend/tampere/featureFlags.tsx

Also enables automatic fixed schedule absences for test environment

Unscheduled summer update to  fix municipal invoicing

---

service/src/main/kotlin/fi/nokiankaupunki/evaka/security/NokiaActionRuleMapping.kt
service/src/main/resources/WEB-INF/templates/nokia/fee-decision/decision.html
service/src/main/resources/WEB-INF/templates/nokia/fee-decision/voucher-value-decision.html
service/src/main/resources/WEB-INF/templates/nokia/shared/common.html

https://voltti.atlassian.net/browse/TREV-1295

Päätöksentekijän nimi päälle (Nokia)

---

frontend/hameenkyro/fiCustomizations.tsx
frontend/kangasala/fiCustomizations.tsx
frontend/lempaala/fiCustomizations.tsx
frontend/nokia/fiCustomizations.tsx
frontend/orivesi/fiCustomizations.tsx
frontend/pirkkala/fiCustomizations.tsx
frontend/tampere/fiCustomizations.tsx
frontend/vesilahti/fiCustomizations.tsx
frontend/ylojarvi/fiCustomizations.tsx
service/src/main/resources/WEB-INF/templates/kangasala/assistance/decision.properties

https://voltti.atlassian.net/browse/TREV-1316
https://voltti.atlassian.net/browse/TREV-1317

Kangasala fixes

---

service/src/main/resources/db/data/pirkkala/afterMigrate__service_need_options.sql

Fee coefficient changes from 60% to 50% on 2024-08-01.

Add service need option starting from 2024-08-01

---

frontend/orivesi/enCustomizations.tsx
frontend/orivesi/fiCustomizations.tsx

https://voltti.atlassian.net/browse/TREV-1322

Update Orivesi accessibility statement

---

service/src/main/resources/WEB-INF/templates/hameenkyro/fee-decision/decision.properties

https://voltti.atlassian.net/browse/TREV-1338

Update email address in hämeenkyrö fee decision

---

service/src/main/resources/db/data/hameenkyro/afterMigrate__holidays.sql
service/src/main/resources/db/data/kangasala/afterMigrate__holidays.sql
service/src/main/resources/db/data/lempaala/afterMigrate__holidays.sql
service/src/main/resources/db/data/nokia/afterMigrate__holidays.sql
service/src/main/resources/db/data/orivesi/afterMigrate__holidays.sql
service/src/main/resources/db/data/pirkkala/afterMigrate__holidays.sql
service/src/main/resources/db/data/tampere/afterMigrate__holidays.sql
service/src/main/resources/db/data/vesilahti/afterMigrate__holidays.sql
service/src/main/resources/db/data/ylojarvi/afterMigrate__holidays.sql

https://voltti.atlassian.net/browse/TREV-1359
https://publicholidays.fi/fi/2025-dates/

Add 2025 holidays

---

service/src/main/kotlin/fi/hameenkyro/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/kangasala/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/lempaala/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/nokiankaupunki/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/orivesi/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/pirkkala/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/tampere/trevaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/vesilahti/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/ylojarvi/evaka/emailclient/config/EmailConfiguration.kt

Bump evaka version and add missing and changed email templates.

Added discussion time reservation email templates and changes

---

service/src/main/kotlin/fi/hameenkyro/evaka/HameenkyroConfig.kt
service/src/main/kotlin/fi/kangasala/evaka/KangasalaConfig.kt
service/src/main/kotlin/fi/lempaala/evaka/LempaalaConfig.kt
service/src/main/kotlin/fi/nokiankaupunki/evaka/NokiaConfig.kt
service/src/main/kotlin/fi/orivesi/evaka/OrivesiConfig.kt
service/src/main/kotlin/fi/pirkkala/evaka/PirkkalaConfig.kt
service/src/main/kotlin/fi/vesilahti/evaka/VesilahtiConfig.kt
service/src/main/kotlin/fi/ylojarvi/evaka/YlojarviConfig.kt

Add daycare placement plan end month-day configs

---

auth/Dockerfile

Use docker hub for keycloak

---

service/src/main/kotlin/fi/hameenkyro/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/kangasala/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/lempaala/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/nokiankaupunki/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/orivesi/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/pirkkala/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/tampere/trevaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/vesilahti/evaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/ylojarvi/evaka/emailclient/config/EmailConfiguration.kt

Identical changes for all municipalities.

Add bulletin subjects to notification emails if sender is municipal

---

infra/deploy/variables/tampere-dev-apps.tfvars
infra/deploy/variables/tampere-prod-apps.tfvars
infra/deploy/variables/tampere-test-apps.tfvars

Update voucher value report freeze schedule

---

.circleci/config.yml

Service build cache was uploaded twice.

Fix service builder cache

---

frontend/package.json
frontend/yarn.lock

This removes ip package which has vulnerability.

Upgrade all transitive dependencies to the latest

---

.circleci/config.yml
frontend/lint.sh

Adds possibility to run `./frontend/lint.sh` & `./frontend/lint.sh --fix` on local environment.

Add frontend lint.sh

---

service/src/main/kotlin/fi/hameenkyro/evaka/security/HameenkyroActionRuleMapping.kt
service/src/main/kotlin/fi/kangasala/evaka/security/KangasalaActionRuleMapping.kt
service/src/main/kotlin/fi/lempaala/evaka/security/LempaalaActionRuleMapping.kt
service/src/main/kotlin/fi/nokiankaupunki/evaka/security/NokiaActionRuleMapping.kt
service/src/main/kotlin/fi/orivesi/evaka/security/OrivesiActionRuleMapping.kt
service/src/main/kotlin/fi/pirkkala/evaka/security/PirkkalaActionRuleMapping.kt
service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt
service/src/main/kotlin/fi/vesilahti/evaka/security/VesilahtiActionRuleMapping.kt
service/src/main/kotlin/fi/ylojarvi/evaka/security/YlojarviActionRuleMapping.kt

Added REPORT_VIEWER access to placement count report

---

frontend/src/e2e/common/translations-check-utils.ts
frontend/src/e2e/tampere.jest.config.ts
frontend/tsconfig.json

IDEA reported many errors for e2e files, this should fix those.

Fix typescript errors

---

service/src/main/kotlin/fi/hameenkyro/evaka/security/HameenkyroActionRuleMapping.kt
service/src/main/kotlin/fi/kangasala/evaka/security/KangasalaActionRuleMapping.kt
service/src/main/kotlin/fi/lempaala/evaka/security/LempaalaActionRuleMapping.kt
service/src/main/kotlin/fi/nokiankaupunki/evaka/security/NokiaActionRuleMapping.kt
service/src/main/kotlin/fi/orivesi/evaka/security/OrivesiActionRuleMapping.kt
service/src/main/kotlin/fi/pirkkala/evaka/security/PirkkalaActionRuleMapping.kt
service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt
service/src/main/kotlin/fi/vesilahti/evaka/security/VesilahtiActionRuleMapping.kt
service/src/main/kotlin/fi/ylojarvi/evaka/security/YlojarviActionRuleMapping.kt

Koskee kaikkia Tampereen seudun kuntia.

Lisätään pedagogisten asiakirjojen lukuoikeus Vaka-johtajille

---

.circleci/config.yml
ecosystem.config.js
service/Dockerfile

Recommended by gradle developers.

Use gradle daemon

---

frontend/tampere/enCustomizations.tsx
frontend/tampere/fiCustomizations.tsx

This reverts commit 1d63b9f843d53ec92afaa87a13b02f63d8a94efa.

Revert "Update preschool info text"

---

service/src/main/kotlin/fi/tampere/trevaka/dev/TampereDevApi.kt
service/src/main/resources/application-trevaka-local.yaml

Makes possible to send invoices & payments in local environment.

Add invoice & payment dev api

---

frontend/vesilahti/enCustomizations.tsx
frontend/vesilahti/featureFlags.tsx
frontend/vesilahti/fiCustomizations.tsx

Includes en translations missing in https://github.com/Tampere/trevaka/pull/1334

Vesilahti preschool application fixes

---

.circleci/config.yml

This might be handy at least in the next couple of weeks.

Add deploy to single environment

---

frontend/hameenkyro/enCustomizations.tsx
frontend/hameenkyro/fiCustomizations.tsx
frontend/kangasala/enCustomizations.tsx
frontend/kangasala/fiCustomizations.tsx
frontend/lempaala/enCustomizations.tsx
frontend/lempaala/fiCustomizations.tsx
frontend/nokia/enCustomizations.tsx
frontend/nokia/fiCustomizations.tsx
frontend/orivesi/enCustomizations.tsx
frontend/orivesi/fiCustomizations.tsx
frontend/pirkkala/enCustomizations.tsx
frontend/pirkkala/fiCustomizations.tsx
frontend/tampere/enCustomizations.tsx
frontend/tampere/fiCustomizations.tsx
frontend/vesilahti/enCustomizations.tsx
frontend/vesilahti/fiCustomizations.tsx
frontend/ylojarvi/enCustomizations.tsx
frontend/ylojarvi/fiCustomizations.tsx

Also replaced `'` with `’` to get rid of ugly differences between adjacent lines in the English translation.

Service application bullet point addition (all municipalities)

---

infra/deploy/evaka-apigw.tf
service/src/main/kotlin/fi/hameenkyro/evaka/HameenkyroConfig.kt
service/src/main/kotlin/fi/kangasala/evaka/KangasalaConfig.kt
service/src/main/kotlin/fi/lempaala/evaka/LempaalaConfig.kt
service/src/main/kotlin/fi/nokiankaupunki/evaka/NokiaConfig.kt
service/src/main/kotlin/fi/orivesi/evaka/OrivesiConfig.kt
service/src/main/kotlin/fi/pirkkala/evaka/PirkkalaConfig.kt
service/src/main/kotlin/fi/tampere/trevaka/TampereConfig.kt
service/src/main/kotlin/fi/vesilahti/evaka/VesilahtiConfig.kt
service/src/main/kotlin/fi/ylojarvi/evaka/YlojarviConfig.kt

Salasanavaatimus: Vähintään 10 merkkiä, yksi numero ja yksi iso kirjain
Montako kirjautumisyritystä voi tehdä tunnissa: 5 kpl

Update password specification

---

frontend/hameenkyro/enCustomizations.tsx
frontend/hameenkyro/fiCustomizations.tsx
frontend/kangasala/enCustomizations.tsx
frontend/kangasala/fiCustomizations.tsx
frontend/lempaala/enCustomizations.tsx
frontend/lempaala/fiCustomizations.tsx
frontend/nokia/enCustomizations.tsx
frontend/nokia/fiCustomizations.tsx
frontend/orivesi/enCustomizations.tsx
frontend/orivesi/fiCustomizations.tsx
frontend/pirkkala/enCustomizations.tsx
frontend/pirkkala/fiCustomizations.tsx
frontend/tampere/enCustomizations.tsx
frontend/tampere/fiCustomizations.tsx
frontend/vesilahti/enCustomizations.tsx
frontend/vesilahti/fiCustomizations.tsx
frontend/ylojarvi/enCustomizations.tsx
frontend/ylojarvi/fiCustomizations.tsx

Mikäli sinulla on muita tuloja, tulee niistä toimittaa tositteet liitteenä. ~~Listan tarvittavista liitteistä löydät lomakkeen alaosasta kohdasta: Tuloihin ja varhaiskasvatusmaksuihin liittyvät liitteet.~~
If you have other income, it must be itemised in an attachment. ~~A list of the required attachments can be found at the bottom of the form under: Attachments related to income and early childhood education fees.~~

Update other income description text

---

infra/deploy/evaka-frontend.tf
infra/deploy/keycloak.tf
infra/deploy/variables/tampere-dev-apps.tfvars

This should used after weakLogin is enabled in frontend.

Add variable to disable auth paths

---

service/src/main/kotlin/fi/lempaala/evaka/invoice/service/ProEInvoiceGenerator.kt
service/src/test/kotlin/fi/lempaala/evaka/invoice/service/LempaalaInvoiceIntegrationClientTest.kt

"tili pitäisi olla 3257, vaihdetaan 3275 tilalle."

Fix invoice account

---

infra/deploy/evaka-apigw.tf
infra/deploy/variables/hameenkyro-prod-apps.tfvars
infra/deploy/variables/hameenkyro-test-apps.tfvars
infra/deploy/variables/tampere-dev-apps.tfvars
infra/deploy/variables/tampere-prod-apps.tfvars
infra/deploy/variables/tampere-test-apps.tfvars
infra/deploy/variables/vesilahti-prod-apps.tfvars
infra/deploy/variables/vesilahti-test-apps.tfvars

These are currently optional in core.

Remove keycloak envs

---

service/src/main/kotlin/fi/tampere/trevaka/bi/BiModels.kt
service/src/main/kotlin/fi/tampere/trevaka/bi/BiQueries.kt
service/src/test/kotlin/fi/tampere/trevaka/bi/ExportBiCsvJobTest.kt

Column last_login is nullable since V504.

Fix employee export

---

service/src/main/resources/WEB-INF/templates/hameenkyro/shared/preschool-correction.properties
service/src/main/resources/WEB-INF/templates/lempaala/shared/preschool-correction.properties
service/src/main/resources/WEB-INF/templates/tampere/shared/preschool-correction.properties
service/src/main/resources/WEB-INF/templates/vesilahti/shared/preschool-correction.properties

Affects preschool decision templates in:
- Hämeenkyrö
- Lempäälä
- Vesilahti
- Tampere

Replaced obsolete Uimalankatu location from all address entries

---

frontend/kangasala/employee.tsx
frontend/kangasala/fiCustomizations.tsx
service/src/main/resources/WEB-INF/templates/kangasala/assistance/decision.properties

Changes `aluejohtaja` to `palvelupäällikkö`.

Update jurisdiction text

---

service/src/test/kotlin/fi/tampere/trevaka/report/PalvelukykykyselyReportTest.kt
service/src/test/resources/application-integration-test.yml
service/src/test/resources/db/data/tampere/afterMigrate__palvelukykykysely_report.sql

Added palvelukykykysely sql to repo and built a simple test to check placement type filtering. Also removed a debug designation for aws sdk that produced unnecessary loglines for all tests.

Palvelukykykysely report sql + test

---

.gitignore
README.md
docker-compose.yml
mise.toml

trevaka:
`mise start`
`mise start --env vesilahti`
evaka:
`mise run espoo`
`mise run espoo --env e2e`

Add mise config

---

docker-compose.yml
service/src/main/resources/application-trevaka-local.yaml
service/src/test/kotlin/trevaka/IntegrationTestConfiguration.kt
service/src/test/resources/application-integration-test.yml

Use s3mock https

---

service/src/test/resources/db/data/tampere/afterMigrate__child_document_export.sql

Fix child document export usage

---

.github/dependabot.yml
service/build.gradle.kts

Refactor xjc

---

infra/deploy/evaka-apigw.tf
infra/deploy/evaka-service.tf

Host headers config should be enough.

Remove unnecessary path patterns config

---

frontend/hameenkyro/employee.tsx
frontend/kangasala/employee.tsx
frontend/lempaala/employee.tsx
frontend/nokia/employee.tsx
frontend/orivesi/employee.tsx
frontend/pirkkala/employee.tsx
frontend/tampere/employee.tsx
frontend/vesilahti/employee.tsx
frontend/ylojarvi/employee.tsx

Tampere updates differ slightly from other municipalities.

Update absence type names and info texts
