Tampere/trevaka

service/src/main/kotlin/fi/tampere/trevaka/TrevakaMain.kt

VOLTTI_ENV based profile selection was not working because there
was a typo (enables_dev_api vs enable_dev_api). Dev api can be
enabled with SPRING_PROFILES_ACTIVE environment variable.

Cleanup main

---

service/src/main/kotlin/fi/tampere/trevaka/TampereConfig.kt
service/src/main/kotlin/fi/tampere/trevaka/dev/TampereDevApi.kt

- added a no-op client bean for a new invoicing feature not used in Tampere
- added the new clock-parameter in Tampere-specific DevApi for compatibility, clock choice defaults to the implementation identical to previously implicit functionality

Compatibility changes and evaka ref update

---

service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt

Granted `UserRole.EARLY_CHILDHOOD_EDUCATION_SECRETARY` permission to update unit staff attendances (realtime) and staff occupancy coefficients

TREV-826 + TREV-848: Additional Trevaka permission grants for early childhood education secretary

---

service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt

Adds following permissions for EARLY_CHILDHOOD_EDUCATION_SECRETARY -role:
- full control of absences of children in associated units (group and child scopes)
- full control of child attendance reservations of children in associated units (child scope)
- read access to placement sketching report if associated to a unit (global scope)

TREV-865: EESEC permission expansion

---

service/src/main/kotlin/fi/tampere/trevaka/security/TampereActionRuleMapping.kt

Granted access rights contingent on user's unit ACL for placement unit of child:
- CHILD
- read documents
- create documents
- DOCUMENT
- update
- delete
- create attachment
- ATTACHMENT
- delete

ECES granted access to child's pedagogic documentation through placement unit ACL

---

frontend/tampere/employee.tsx
frontend/tampere/fiCustomizations.tsx
service/src/main/kotlin/fi/tampere/trevaka/template/config/TemplateConfiguration.kt
service/src/main/resources/WEB-INF/templates/tampere/assistance-preschool/decision.html
service/src/main/resources/WEB-INF/templates/tampere/assistance-preschool/decision.properties
service/src/main/resources/WEB-INF/templates/tampere/assistance/decision.properties
service/src/test/kotlin/fi/tampere/trevaka/assistanceneed/decision/PreschoolAssistanceNeedDecisionServiceTest.kt

New stuff:
- new template for preschool assistance need decision PDF generation
- new properties file for above template texts
- new integration test for above PDF generation with "valid" test data
Updated stuff:
- employee translations
-  added Tampere-specific info text content for the draft decision editing view
-  new appeal instructions for preschool assistance need decisions in employee UI
- citizen translations
- new appeal instructions for preschool assistance decisions in citizen UI
- early education assistance need decision template properties
- fixed the missing spaces issue in appeal instructions

Preschool assistance need decision content changes

---

service/build.gradle.kts
service/src/main/kotlin/fi/tampere/trevaka/emailclient/config/EmailConfiguration.kt
service/src/main/kotlin/fi/tampere/trevaka/invoice/config/InvoiceConfiguration.kt
service/src/main/kotlin/fi/tampere/trevaka/titania/TitaniaController.kt
service/src/main/kotlin/trevaka/Main.kt
service/src/main/kotlin/trevaka/TampereComponentScan.kt
service/src/test/kotlin/fi/tampere/trevaka/AbstractIntegrationTest.kt

This allows us to use service for multiple municipalities.
There are still some hard-coded values in `build.gradle.kts` but this is already a good start.

Remove hard-coded service profile

---

auth/Dockerfile

Moved from environment variables to fix warning on startup: "build time non-cli properties were found, but will be ignored during run time"

Update auth build params

---

service/src/main/kotlin/fi/kangasala/evaka/KangasalaInvoiceProductProvider.kt
service/src/main/kotlin/fi/lempaala/evaka/LempaalaInvoiceProductProvider.kt

Throwing an error is causing unnecessary alarms.

Add InvoiceProductProvider#products empty implementation

---

service/src/main/kotlin/fi/ylojarvi/evaka/security/YlojarviActionRuleMapping.kt

https://voltti.atlassian.net/browse/TREV-1199
Enabled access to settings in Ylöjärvi, others were already hidden

TREV-1199 - Hide settings menu from 2nd & 3rd wave (except ylöjärvi)

---

service/src/main/resources/WEB-INF/templates/hameenkyro/daycare/decision.properties
service/src/main/resources/WEB-INF/templates/hameenkyro/daycare/voucher/decision.properties
service/src/main/resources/WEB-INF/templates/kangasala/daycare/decision.properties
service/src/main/resources/WEB-INF/templates/kangasala/daycare/voucher/decision.properties
service/src/main/resources/WEB-INF/templates/lempaala/daycare/decision.properties
service/src/main/resources/WEB-INF/templates/lempaala/daycare/voucher/decision.properties
service/src/main/resources/WEB-INF/templates/nokia/daycare/decision.properties
service/src/main/resources/WEB-INF/templates/nokia/daycare/voucher/decision.properties
service/src/main/resources/WEB-INF/templates/orivesi/daycare/decision.properties
service/src/main/resources/WEB-INF/templates/orivesi/daycare/voucher/decision.properties
service/src/main/resources/WEB-INF/templates/pirkkala/daycare/decision.properties
service/src/main/resources/WEB-INF/templates/pirkkala/daycare/voucher/decision.properties
service/src/main/resources/WEB-INF/templates/tampere/daycare/decision.properties
service/src/main/resources/WEB-INF/templates/tampere/daycare/voucher/decision.properties
service/src/main/resources/WEB-INF/templates/vesilahti/daycare/decision.properties
service/src/main/resources/WEB-INF/templates/ylojarvi/daycare/decision.properties
service/src/main/resources/WEB-INF/templates/ylojarvi/daycare/voucher/decision.properties

Use same instruction text and logic for:
- municipal daycare decision
- voucher daycare decision
- preschool daycare decision
- preschool club decision

Standardizing income statement instructions in decision PDFs across municipalities

---

.circleci/config.yml

Image cimg/aws doesn't seem to get updates. The only thing we need is aws-cli, and aws-cli orb will install it when missing.

Remove aws executor

---

service/src/main/kotlin/fi/lempaala/evaka/invoice/config/InvoiceConfiguration.kt
service/src/test/kotlin/fi/lempaala/evaka/invoice/LempaalaInvoiceNumberTest.kt

The first series start was 1: https://github.com/Tampere/trevaka/commit/82e92501ca375a3acaf97625928d55d094588af0#diff-b8e670be8f943ec8562d70a3506ec9f0917827b715ede8dd23ef7f3cf1a08475R36
Then it was changed to 5400042258 just before production: https://github.com/Tampere/trevaka/commit/bcb8f1acfd11a5f74044f10c5fc5d994bd6a221d
Next number should be 54000001, but at least test environment includes some invoice numbers starting from 1.

Fix next invoice number

---

service/src/main/kotlin/fi/tampere/trevaka/invoice/config/InvoiceConfiguration.kt
service/src/test/kotlin/fi/tampere/trevaka/invoice/config/InvoiceConfigurationIT.kt

Interface member implemented using the boolean-returning query from the old implementation to filter the child list parameter of the new interface. Also fixed missing holiday-table dependency.

Add an implementation of getFreeChildren for Tampere config

---

infra/deploy/evaka-service.tf
infra/deploy/variables/hameenkyro-test-apps.tfvars
infra/deploy/variables/kangasala-test-apps.tfvars
infra/deploy/variables/lempaala-test-apps.tfvars
infra/deploy/variables/nokia-test-apps.tfvars
infra/deploy/variables/orivesi-test-apps.tfvars
infra/deploy/variables/pirkkala-test-apps.tfvars
infra/deploy/variables/tampere-dev-apps.tfvars
infra/deploy/variables/tampere-test-apps.tfvars
infra/deploy/variables/vesilahti-test-apps.tfvars
infra/deploy/variables/ylojarvi-test-apps.tfvars

Also disables the integration in `tampere-test` because we only got one account for each municipality.

Enable suomi.fi-messages rest (prod)

---

.github/dependabot.yml

We don't need to update terraform providers daily.

Update dependabot interval for terraform updates

---

.github/dependabot.yml
compose/s3mock.Dockerfile
docker-compose.yml

It should support docker compose files now:
https://github.blog/changelog/2025-02-25-dependabot-version-updates-now-support-docker-compose-in-general-availability/

Remove workaround for dependabot

---

service/src/main/kotlin/fi/hameenkyro/evaka/HameenkyroConfig.kt
service/src/main/kotlin/fi/kangasala/evaka/KangasalaConfig.kt
service/src/main/kotlin/fi/lempaala/evaka/LempaalaConfig.kt
service/src/main/kotlin/fi/nokiankaupunki/evaka/NokiaConfig.kt
service/src/main/kotlin/fi/orivesi/evaka/OrivesiConfig.kt
service/src/main/kotlin/fi/pirkkala/evaka/PirkkalaConfig.kt
service/src/main/kotlin/fi/vesilahti/evaka/VesilahtiConfig.kt
service/src/main/kotlin/fi/ylojarvi/evaka/YlojarviConfig.kt

This should be enough for holiday questionnaire answers to work correctly.
Note: Tampere uses custom logic so this config should still be `false`.

Enable freeAbsenceGivesADailyRefund (for free summer holiday)

---

service/.dockerignore

e.g. `Dockerfile` edit doesn't always require full build now.

Update service .dockerignore

---

.circleci/config.yml

Useful if we change value in parameter store and want to restart containers.

Add force_new_deployment parameter

---

infra/deploy/evaka-service.tf

Emergency disabling of metadata migrations due to a bug in the scheduled job when metadata not available.

Disable all metadata migrations

---

service/src/main/resources/db/data/tampere/afterMigrate__assistance_action_options.sql

Adds 
- 1 `DAYCARE` option 
- 7 `PRESCHOOL` options. 
Moves 2 `DAYCARE` options to `PRESCHOOL`. 
Changes names of 2 `DAYCARE` options slightly.
New options have `valid_from` dates, old ones don't.

Update Tampere assistance action options
